version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: frauduser
      POSTGRES_PASSWORD: fraudpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # SQL initialization script

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    depends_on:
      - kafka
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/frauddb
      SPRING_DATASOURCE_USERNAME: frauduser
      SPRING_DATASOURCE_PASSWORD: fraudpass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: docker

  fraud-service:
    build:
      context: ./fraud-detection-service
    container_name: fraud-service
    depends_on:
      - kafka
      - postgres
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/frauddb
      SPRING_DATASOURCE_USERNAME: frauduser
      SPRING_DATASOURCE_PASSWORD: fraudpass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: docker

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      - SMTP_KEY_VALUE=${SMTP_KEY_VALUE}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - FROM_EMAIL=${FROM_EMAIL}
      - BREVO_USERNAME=${BREVO_USERNAME}
      - BREVO_HOST=${BREVO_HOST}
      - BREVO_PASSWORD=${BREVO_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data: