spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/frauddb
    username: frauduser
    password: fraudpass